
export const quotes = [
    "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos. - Michael Jordan",
    "Solos podemos hacer muy poco; unidos podemos hacer mucho. - Helen Keller",
    "La unidad es la fuerza... cuando hay trabajo en equipo y colaboración, se pueden lograr cosas maravillosas. - Mattie Stepanek",
    "Ninguno de nosotros es tan bueno como todos nosotros juntos. - Ray Kroc",
    "Individualmente, somos una gota. Juntos, somos un océano. - Ryunosuke Satoro",
    "La fortaleza del equipo es cada miembro individual. La fortaleza de cada miembro es el equipo. - Phil Jackson",
    "Llegar juntos es el principio. Mantenerse juntos, es el progreso. Trabajar juntos es el éxito. - Henry Ford",
    "La cooperación es la convicción de que nadie puede llegar allí a menos que todos lleguen allí. - Virginia Burden",
    "Lo que hay que hacer es unir a la gente. Si unes a la gente, obtienes poder. - Stokely Carmichael",
    "Un bote no va hacia adelante si cada uno rema a su propia manera. - Proverbio Swahili",
    "Un grupo se convierte en un equipo cuando cada miembro está lo suficientemente seguro de sí mismo y de su contribución como para alabar las habilidades de los demás. - Norman Shidle",
    "Si quieres ir rápido, ve solo. Si quieres llegar lejos, ve acompañado. - Proverbio Africano",
    "El trabajo en equipo es el secreto que hace que la gente común logre resultados poco comunes. - Ifeanyi Onuoha",
    "El compromiso individual con un esfuerzo grupal: eso es lo que hace que un equipo funcione, una empresa funcione, una sociedad funcione, una civilización funcione. - Vince Lombardi",
    "El trabajo en equipo es la capacidad de trabajar juntos hacia una visión común. La capacidad de dirigir los logros individuales hacia los objetivos de la organización. Es el combustible que permite que la gente común alcance resultados poco comunes. - Andrew Carnegie",
    "La mejor manera de empezar es dejar de hablar y empezar a hacer. - Walt Disney",
    "El éxito no es definitivo, el fracaso no es fatal: es el coraje para continuar lo que cuenta. - Winston Churchill",
    "La única forma de hacer un gran trabajo es amar lo que haces. - Steve Jobs",
    "Cree que puedes y ya estás a medio camino. - Theodore Roosevelt",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "No mires el reloj; haz lo que él hace. Sigue adelante. - Sam Levenson",
    "La calidad no es un acto, es un hábito. - Aristóteles",
    "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra. - Jimmy Johnson",
    "Para tener éxito, tu deseo de éxito debe ser mayor que tu miedo al fracaso. - Bill Cosby",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario. - Vidal Sassoon",
    "No se trata de tener las oportunidades adecuadas, se trata de manejar las oportunidades correctamente. - Mark Hunter",
    "La excelencia no es una habilidad. Es una actitud. - Ralph Marston",
    "Si no estás dispuesto a arriesgar lo inusual, tendrás que conformarte con lo ordinario. - Jim Rohn",
    "El ingrediente más importante es levantarse y hacer algo. Así de simple. Muchas personas tienen ideas, pero solo algunas deciden hacer algo hoy. No mañana. No la próxima semana. Sino hoy. - Nolan Bushnell",
    "La gente que está lo suficientemente loca como para pensar que puede cambiar el mundo, es la que lo hace. - Anónimo",
    "La forma de empezar es dejar de hablar y empezar a hacer. - Walt Disney",
    "Con autodisciplina casi todo es posible. - Theodore Roosevelt",
    "La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas. - Jim Ryun",
    "La disciplina es el puente entre las metas y los logros. - Jim Rohn",
    "Los grandes logros siempre tienen lugar en el marco de una alta expectativa. - Charles Kettering",
    "El trabajo en equipo divide el trabajo y multiplica los resultados.",
    "Juntos es mejor.",
    "El espíritu de equipo es lo que da a muchas empresas una ventaja sobre sus competidores.",
    "Un equipo exitoso es un grupo de muchas manos y una sola mente.",
    "Los equipos comparten la carga y dividen el dolor.",
    "Cuando 'yo' es reemplazado por 'nosotros', incluso la enfermedad se convierte en bienestar.",
    "El trabajo en equipo hace que el sueño funcione.",
    "Un equipo es más que un conjunto de personas. Es un proceso de dar y recibir.",
    "No hay problema que no podamos resolver juntos, y muy pocos que podamos resolver por nosotros mismos.",
    "El trabajo en equipo es la esencia de la vida.",
    "Si quieres levantar a ti mismo, levanta a alguien más. - Booker T. Washington",
    "La eficiencia es hacer mejor lo que ya se está haciendo. - Peter Drucker",
    "Si todos avanzan juntos, el éxito se encarga de sí mismo.",
    "La fuerza del equipo está en cada miembro. La fuerza de cada miembro es el equipo.",
    "La colaboración permite a los maestros trabajar juntos para lograr un objetivo común y compartir la carga de trabajo."
];
